dist: trusty
sudo: required
language: Java
jdk: oraclejdk8

stages:
  - name: compile
  - name: test
  - name: deploy
  - name: integration_test


jobs:
  include:
    - stage: compile
      install: mvn --version
      script:
        - mvn compile
    - stage: test
      install: mvn --version
      script:
        - mvn test
    - stage: deploy
      install: mvn --version
      script:
        - mvn package
        - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
        - docker build -t registry.heroku.com/coursersoi/web .
        - docker push registry.heroku.com/coursersoi/web
        - docker run --rm -e HEROKU_API_KEY=$API_KEY wingrunr21/alpine-heroku-cli container:release web --app coursersoi
    - stage: integration_test
      install: mvn --version
      script:
        - curl -X GET  https://coursersoi.herokuapp.com/
