dist: trusty
sudo: false
language: Java
jdk: oraclejdk8

stages:
  - name: compile
  - name: test
  - name: deploy


jobs:
  include:
    - stage: compile
      install: mvn --version
      script:
        - mvn compile
    - stage: test
      install: mvn --version
      script:
        - mvn test
    - stage: deploy
      install: mvn --version
      script:
        - mvn package
        - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
        - docker build -t registry.heroku.com/rsoi-lab1/web .
        - docker push registry.heroku.com/rsoi-lab1/web

