language: generic

stages:
  - name: test
  - name: deploy


jobs:
  include:
    - stage: test
      language: java
      jdk:
      - oraclejdk8
      install: mvn --version
      script:
        - mvn install
        - mvn test
    - stage: deploy
      language: java
      jdk:
      - oraclejdk8
      install: mvn --version
      script:
        - mvn install
        - mvn package
        - docker build -t rsoitest .

