dist: trusty
sudo: false
language: Java
jdk: oraclejdk8

stages:
  - name: compile
  - name: test
  - name: deploy


jobs:
  include:
    - stage: compile
      install: mvn --version
      script:
        - mvn compile
    - stage: test
      install: mvn --version
      script:
        - mvn test
    - stage: deploy
      install: mvn --version
      script:
        - mvn package
        - docker build -t rsoitest .

